# docker-compose.yml
services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: "2g"

  analysis:
    build:
      context: .
      target: final
    volumes:
      - ./data:/air_monitoring/data
    working_dir: /air_monitoring
    depends_on:
      - selenium
    ports:
      - "8787:8787"    # RStudio Server
    environment:
      - PASSWORD=secret
      - USER=RStudio
      - REMOTE_DRIVER_URL=http://selenium:4444/wd/hub

# Usage:
#   docker-compose up --build
#   # Visit http://localhost:8787 for RStudio
#   # RStudio user: RStudio | passwd: secret
